<?php declare(strict_types=1);

namespace noxkiwi\spotigame\Context;

use Exception;
use noxkiwi\core\ErrorHandler;
use noxkiwi\core\Helper\LinkHelper;
use noxkiwi\core\Helper\WebHelper;
use noxkiwi\spotigame\Exception\GameOverException;
use noxkiwi\spotigame\GameEntity\GameMode\GameMode;
use noxkiwi\spotigame\GameEntity\Sitting\Sitting;
use noxkiwi\spotigame\Helper\SpotifyRedirect;
use noxkiwi\spotigame\Model\SittingModel;
use noxkiwi\spotigame\Verification\Verification;
use function header;

/**
 * I am the main view context.
 *
 * @package      noxkiwi\spotigame\Context
 * @author       Jan Nox <jan@nox.kiwi>
 * @license      https://nox.kiwi/license
 * @copyright    2023 noxkiwi
 * @version      1.0.0
 * @link         https://nox.kiwi/
 */
class GameContext extends AuthenticatedSpotigameContext
{
    public function isAllowed(): bool
    {
        parent::isAllowed(); // TODO: Change the autogenerated stub

        // Fetch sitting!
        try {
            $this->sitting = $this->getSitting();
            $this->response->set('sitting', $this->sitting);
        } catch (Exception $e) {
            LinkHelper::forward(SpotifyRedirect::TO_LOBBY_WELCOME);
            return false;
        }
        return true;
    }

    /**
     * I will return the current Player's current Sitting.
     * @return \noxkiwi\spotigame\GameEntity\Sitting\Sitting
     */
    private function getSitting(): Sitting
    {
        try {
            return SittingModel::getInstance()->fetchSitting($this->player);
        } catch (Exception) {
            $hostName = $this->environment->get('server>hostname', 'https://spotigame.nox.kiwi/');
            header("Location: $hostName?context=sitting&action=create");
            exit(WebHelper::HTTP_TEMPORARY_REDIRECT);
        }
    }

    /**
     * I will verify the user's answers from the Request.
     *
     * @return void
     * @todo: Decode the requests partials (Questions, Sitting, Song, User) into  objects.
     * @todo: Implement vicious OOP structure for the Verification.
     *
     * @todo: Implement better JSON response.
     */
    protected function actionVerify(): void
    {
        $this->request->set('template', 'json');
        // Unpack the request.

        $move = $this->sitting->getCurrentMove();
        $postedStuff = [
            'Questions' => $this->request->get('Questions'),
            'Sitting' => $this->request->get('Sitting'),
            'Song' => $this->request->get('Song'),
            'User' => $this->request->get('User'),
            'Move' => $move
        ];

        // Create verification object
        $verification = new Verification($this->player, $move, $postedStuff);

        // Run the verification object.
        $verification->verify();

        // Store the verification.
        $verification->save();

        $this->response->flush();
        $this->response->set('Verification', $verification);
    }


    /**
     * @return void
     * @todo: Implement better JSON response.
     * @todo: split into "ask" and "next" actions. Also add "play" action.
     */
    protected function actionAsk(): void
    {
        $this->request->set('template', 'json');

        // Fetch the (next) move.
        try {
            if ($this->request->exists('next')) {
                $move = $this->sitting->getNextMove();
            } else {
                $move = $this->sitting->getCurrentMove();
            }
        } catch (GameOverException) {
            $this->sitting->finishRound($this->player);
            LinkHelper::forward("/a/lobby/results/{$this->sitting->id}");
        } catch (Exception $exception) {
            ErrorHandler::handleException($exception, E_USER_NOTICE);

            return;
        }

        // Check if the user requested to start playback of the song
        if (($this->request->exists('next') || $this->request->exists('play')) || $this->request->exists('code')) {
            $this->player->playSong($move->Song);

            LinkHelper::forward('/a/lobby');
        }

        // Put the move into the response for front-end.
        $this->response->flush();
        $this->response->set('Move', $move->buildSetup($this->player, new GameMode()));
    }

}
